#!/bin/bash
set -eux

# 1. Create the Mount Unit
# This tells systemd: "If you see a disk labeled config-2, mount it here."
cat <<EOF > /etc/systemd/system/mnt-config.mount
[Unit]
Description=Mount Ironic Config Drive
ConditionPathExists=/dev/disk/by-label/config-2

[Mount]
What=/dev/disk/by-label/config-2
Where=/mnt/config
Type=auto
Options=ro,fail

[Install]
WantedBy=multi-user.target
EOF

# 3. Enable the mount unit
systemctl enable mnt-config.mount
